#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication gmshToFoam Zalesak.msh

cp constant/boundary.org constant/polyMesh/boundary

cp 0/alpha.water.org 0/alpha.water

runApplication decomposePar

runParallel $(getApplication)

runApplication reconstructPar

runApplication foamToVTK

